#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then

clear
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
echo -e '\e[38;5;82m' "You must run \"install_pmxkcd\" script using \"sudo\" or as the root user."
echo -e '\e[38;5;82m' "Hint : \"sudo bash ./install_pmxkcd\" or \"su -c 'bash ./install_pmxkcd'\""
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
tput sgr0
exit 1
fi

if [ ! -f pmxkcd.tar.gz ]; then

clear
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
echo -e '\e[38;5;82m' "Required archive \"pmxkcd.tar.gz\" is missing!"
echo -e '\e[38;5;82m' "Can not continue!!! Installation is aborted!"
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
tput sgr0
exit 1
fi

type yad >/dev/null 2>&1 || { clear; echo ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo ""; echo -e '\e[38;5;82m' "Required program dependency \"yad\" is missing"; echo -e '\e[38;5;82m' "\"yad\" as a package available in some distros"; echo -e '\e[38;5;82m' "If it is not available in your distro's repo"; echo -e '\e[38;5;82m' "You can download yad from the following URLs"; echo ""; echo -e '\e[38;5;82m' "https://sourceforge.net/projects/yad-dialog/"; echo -e '\e[38;5;82m' "http://pkgs.org/download/yad"; echo -e '\e[38;5;82m' "http://www.ubuntuupdates.org/package_metas?exact_match=1&q=yad"; echo ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo ""; tput sgr0; exit 1; }

work_dir=$(mktemp -d)

tar -xzf pmxkcd.tar.gz --directory "$work_dir"

cd "$work_dir" || { clear; echo ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo ""; echo -e '\e[38;5;82m' "Something  went wrong!!! Aborted!!!"; echo ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo ""; tput sgr0; exit 1; }

type jq >/dev/null 2>&1

RETVAL=$?

case "$RETVAL" in

0)
pmxk_cp=$(which cp)
"$pmxk_cp" pmxkcd /usr/local/bin
chmod 755 /usr/local/bin/pmxkcd
"$pmxk_cp" pmxkcd.desktop /usr/share/applications
chmod 644 /usr/share/applications/pmxkcd.desktop
"$pmxk_cp" {pmxkcd_icon.png,pmxkcd_logo.png} /usr/share/pixmaps
chmod 644 /usr/share/pixmaps/pmxkcd_icon.png
chmod 644 /usr/share/pixmaps/pmxkcd_logo.png
;;

*)
pmxk_cp=$(which cp)
work_bit=$(getconf LONG_BIT)
"$pmxk_cp" pmxkcd /usr/local/bin
chmod 755 /usr/local/bin/pmxkcd
"$pmxk_cp" pmxkcd.desktop /usr/share/applications
chmod 644 /usr/share/applications/pmxkcd.desktop
"$pmxk_cp" {pmxkcd_icon.png,pmxkcd_logo.png} /usr/share/pixmaps
chmod 644 /usr/share/pixmaps/pmxkcd_icon.png
chmod 644 /usr/share/pixmaps/pmxkcd_logo.png
if [[ "$work_bit" == 32 ]]; then
"$pmxk_cp" jq-linux32 /usr/local/bin/jq
chmod 755 /usr/local/bin/jq
else
"$pmxk_cp" jq-linux64 /usr/local/bin/jq
chmod 755 /usr/local/bin/jq
fi
;;

esac

cd "$HOME" || { clear; echo ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo -e '\e[38;5;82m' "Something  went wrong!!! Aborted!!!"; echo ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo ""; tput sgr0; exit 1; }

pmxk_rm=$(which rm)
"$pmxk_rm" -rf "$work_dir"

clear
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
echo -e '\e[38;5;82m' "Installation of \"pmxkcd\" is successfull!!!"
echo -e '\e[38;5;82m' "You can run \"pmxkcd\" from the main menu or"
echo -e '\e[38;5;82m' "by running \"pmxkcd\" command from terminal."
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
tput sgr0
exit 0
