#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then

clear
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
echo -e '\e[38;5;82m' "You must run \"remove_pmxkcd\" script using \"sudo\" or as the root user."
echo -e '\e[38;5;82m' "Hint : \"sudo bash ./remove_pmxkcd\" or \"su -c 'bash ./remove_pmxkcd'\""
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
tput sgr0
exit 1
fi

type pmxkcd >/dev/null 2>&1 || { clear; echo ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo ""; echo -e '\e[38;5;82m' "\"pmxkcd\" is not installed! Nothing to remove!"; echo ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo ""; tput sgr0; exit 1; }

pmxk1="/usr/local/bin/pmxkcd"
pmxk2="/usr/local/bin/jq"
pmxk3="/usr/share/applications/pmxkcd.desktop"
pmxk4="/usr/share/pixmaps/pmxkcd_icon.png"
pmxk5="/usr/share/pixmaps/pmxkcd_logo.png"
pmxk_rm=$(which rm)

if [ -f "$pmxk1" ]; then
"$pmxk_rm" -f "$pmxk1"
fi

if [ -f "$pmxk2" ]; then
"$pmxk_rm" -f "$pmxk2"
fi

if [ -f "$pmxk3" ]; then
"$pmxk_rm" -f "$pmxk3"
fi

if [ -f "$pmxk4" ]; then
"$pmxk_rm" -f "$pmxk4"
fi

if [ -f "$pmxk5" ]; then
"$pmxk_rm" -f "$pmxk5"
fi

clear
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
echo -e '\e[38;5;82m' "Successfully removed \"pmxkcd\"!"
echo ""
{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
echo ""
exit 0
